One function per service
devsapp/fc-canary pull request #1
Opened 2022-05-05 01:35 UTC by crazylnx

2022-05-06 13:42 UTC, lowkeyrd requested changes
canaryStep.js、canaryPlan.js、canaryWeight.js、linerStep.js有大量逻辑都是重复的，可以抽成一个公共的canaryWorker类，canaryPlan、canaryStep、canaryWeight、linerStep 只做计算逻辑，返回一个plan数组，交给canaryWorker来执行plan

2022-05-06 13:42 UTC, lowkeyrd commented on src/bin/fcHelper.js
> +class FcHelper {
为什么会有两个fcHelpler和functionHelpler? 做的不是一样的事情吗

2022-05-06 13:42 UTC, lowkeyrd commented on src/bin/fcHelper.js
> +          throw new Error(e);
这段throw和上一个else分支有什么区别吗？

2022-05-06 13:42 UTC, lowkeyrd commented on src/bin/fcHelper.js
> +const Client = require('@alicloud/fc-open20210406').default;
这个bin目录比较奇怪，建议挪到libs/fc下

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/validate/validateArgs.js
> +  if (serviceName == undefined) {
这种校验没啥意义吧，因为serviceName是作为函数参数传递的，举个例子：validateParams(mylog, 'demo-function')，也就是将functionName作为serviceName传递了，此时校验是通过的，但实际上是有问题的。
如果要做强校验，函数参数可以定义成一个object，例如：
```suggestion
  async function validateParams(params) {
      const { logger, serviceName, functionName } = params
      if (serviceName) {}
  }
```

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/validate/validateArgs.js
> +  if (baseVersionArgs != undefined) {
改成如下写法即可
```suggestion
  if (baseVersionArgs) {
```

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/validate/validateArgs.js
> +    if (serviceDeployed !== service) {
既然args的service一定要和props相同，那是不是args里就不需要定义serviceName了

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/validate/validateArgs.js
> +    if (serviceDeployed !== service) {
既然args的service一定要和props相同，那是不是args里就不需要定义serviceName了

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/validate/validateArgs.js
> +        if (plan.weight == undefined) {
类型判断不用各个条件都判断一遍，直接采用assert会非常方便
```suggestion
        assert(plan.weight > 0 && plan.weight < 100, 'weight must be a number and  between 1 and 100')
```

2022-05-06 13:42 UTC, lowkeyrd commented on src/lib/canary/linerStep.js
> +  weightCount = (weightCount * 3 + canaryWeight * 3) / 3;
weightCount这么取值的目的是？

2022-05-07 01:40 UTC, crazylnx commented on src/bin/fcHelper.js
> +const Client = require('@alicloud/fc-open20210406').default;
ok

2022-05-07 01:40 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +  if (serviceName == undefined) {
学习到了

2022-05-07 01:42 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +  if (baseVersionArgs != undefined) {
学习到了

2022-05-07 01:56 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +        if (plan.weight == undefined) {
学习到了

2022-05-07 16:37 UTC, crazylnx commented on src/bin/fcHelper.js
> +class FcHelper {
fixed

2022-05-07 16:37 UTC, crazylnx commented on src/bin/fcHelper.js
> +          throw new Error(e);
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/bin/fcHelper.js
> +const Client = require('@alicloud/fc-open20210406').default;
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +  if (serviceName == undefined) {
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +    if (serviceDeployed !== service) {
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +    if (serviceDeployed !== service) {
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/lib/validate/validateArgs.js
> +        if (plan.weight == undefined) {
fixed

2022-05-07 16:38 UTC, crazylnx commented on src/lib/canary/linerStep.js
> +  weightCount = (weightCount * 3 + canaryWeight * 3) / 3;
fixed

2022-05-11 04:48 UTC, lowkeyrd approved these changes
LGTM、

2022-05-11 04:48 UTC, merged